Ajustes

diff --git a/bin/ps-user-change-password b/bin/ps-user-change-password
--- a/bin/ps-user-change-password
+++ b/bin/ps-user-change-password
@@ -1,14 +1,32 @@
 #!/bin/bash
 set -e
 
-USERNAME="$1"
-PASS="$2"
+USERNAME="${1:-}"
+PASS="${2:-}"
 
-# Includes
-source "/usr/local/painelstream/func/main.sh"
+# --------------------------
+# Funções
+# --------------------------
+erro() { echo "{\"status\":\"error\",\"message\":\"$1\"}" >&2; exit 1; }
+sucesso() { echo "{\"status\":\"success\",\"message\":\"$1\",\"data\":{\"user\":\"$USERNAME\"}}"; exit 0; }
 
-validar_usuario_pass "$USERNAME" "$PASS"
+# --------------------------
+# Validações individuais
+# --------------------------
+[[ -z "$USERNAME" ]] && erro "usuario obrigatorio"
+[[ ! "$USERNAME" =~ ^[a-z]{6,10}$ ]] && erro "usuario invalido"
 
+set +e
+!id "$USERNAME" &>/dev/null
+[[ $? -eq 0 ]] && erro "usuario não existe"
+set -e
+
+[[ -z "$PASS" ]] && erro "senha obrigatoria"
+[[ "$PASS" =~ [[:space:]] ]] && erro "senha nao pode conter espacos"
+
+# --------------------------
+# Altera Senha
+# --------------------------
 echo "$USERNAME:$PASS" | sudo chpasswd
 
 sucesso "Senha alterada com sucesso" "{\"user\":\"$USERNAME\"}"
